# permissions for end users to view flagsmiths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flagsmith-viewer-role
rules:
- apiGroups:
  - charts.flagsmith.com
  resources:
  - flagsmiths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.flagsmith.com
  resources:
  - flagsmiths/status
  verbs:
  - get
