apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: flagsmith-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Flagsmith is a feature flag, remote config and AB testing platform
  displayName: Flagsmith
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - testaXXX
  - testbXXX
  links:
  - name: Kubernetes Operator
    url: https://flagsmith-operator.domain
  maintainers:
  - email: support@flagsmith.com
    name: Ben Rometsch
  maturity: alpha
  provider:
    name: Flagsmith
    url: https://www.flagsmith.com/
  version: 0.0.0
